<?php

declare(strict_types=1);

namespace Quonain\SmartResponse\Support;

/** Creates signed webhook bodies without coupling the package to a HTTP client. */
final class WebhookPayload
{
    /**
     * @param array<string, mixed> $meta
     * @return array<string, mixed>
     */
    public static function create(string $event, mixed $data = null, array $meta = [], ?string $secret = null): array
    {
        $body = ['event' => $event, 'data' => $data, 'meta' => $meta, 'timestamp' => time()];
        $encoded = json_encode($body, JSON_THROW_ON_ERROR);

        if ($secret !== null) {
            $body['signature'] = hash_hmac('sha256', $encoded, $secret);
        }

        return $body;
    }

    /**
     * Verify a payload signature generated by create().
     *
     * The payload is encoded with the same JSON options used for signing so
     * receivers can validate the body without a framework-specific client.
     */
    /** @param array<string, mixed> $payload */
    public static function verify(array $payload, string $secret, string $signature): bool
    {
        $provided = strtolower(trim($signature));
        $expected = hash_hmac(
            'sha256',
            json_encode(self::withoutSignature($payload), JSON_THROW_ON_ERROR),
            $secret,
        );

        return hash_equals($expected, $provided);
    }

    /** @return array<string, mixed> */
    /**
     * @param array<string, mixed> $payload
     * @return array<string, mixed>
     */
    private static function withoutSignature(array $payload): array
    {
        unset($payload['signature']);

        return $payload;
    }
}
